stages:
  - build
  - deploy

variables:
  GCLOUD_PROJECT_ID: $GCP_PROJECT_ID
  IMAGE: gcr.io/$GCLOUD_PROJECT_ID/your-app-name
  SERVICE_NAME: sdp3-service-account@sdp3-403516.iam.gserviceaccount.com
  REGION: us-central1
  FRONTEND_DIR: frontend/

before_script:
  - echo $GCP_SERVICE_KEY > gcloud-service-key.json
  - docker run --name gcloud-config google/cloud-sdk gcloud auth activate-service-account --key-file=gcloud-service-key.json
  - docker cp gcloud-config:/root/.config/gcloud /root/.config/gcloud
  - docker rm gcloud-config

build:
  stage: build
  script:
    - cd $FRONTEND_DIR
    - docker build -t $IMAGE:$CI_COMMIT_REF_SLUG .
    - docker run --name gcloud-config google/cloud-sdk gcloud auth configure-docker --quiet
    - docker push $IMAGE:$CI_COMMIT_REF_SLUG

deploy:
  stage: deploy
  script:
    - docker run --name gcloud-config google/cloud-sdk gcloud run deploy $SERVICE_NAME
      --image $IMAGE:$CI_COMMIT_REF_SLUG
      --platform managed
      --region $REGION
      --allow-unauthenticated
  only:
    - main
